// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VroomParts.Data;

#nullable disable

namespace VroomParts.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250306230541_AddCarPartImages")]
    partial class AddCarPartImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VroomParts.Models.CarPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VehicleCompatibility")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CarParts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAdded = new DateTime(2024, 5, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "High-performance brake pads for sport cars.",
                            ImageUrl = "/images/radio_astra_h_1.jpg",
                            Name = "Brake Pads",
                            Price = 59.99m,
                            VehicleCompatibility = "BMW M3, Audi A4, Mercedes C-Class"
                        },
                        new
                        {
                            Id = 2,
                            DateAdded = new DateTime(2024, 4, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Long-lasting air filter for better engine efficiency.",
                            ImageUrl = "/images/radio_astra_h_2.jpg",
                            Name = "Air Filter",
                            Price = 29.99m,
                            VehicleCompatibility = "Toyota Corolla, Honda Civic, Ford Focus"
                        },
                        new
                        {
                            Id = 3,
                            DateAdded = new DateTime(2024, 3, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Platinum spark plugs for improved fuel efficiency.",
                            ImageUrl = "/images/radio_astra_h_3.jpg",
                            Name = "Spark Plugs",
                            Price = 15.99m,
                            VehicleCompatibility = "Ford Mustang, Chevrolet Camaro, Dodge Charger"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
